version: '3'

services:
  gcloud:
    image: google/cloud-sdk:alpine
    volumes:
      - './.credentials:/out'

  tf:
    image: hashicorp/terraform:1.1.6
    volumes:
      - './deploy:/opt/app'
      - './dist:/dist'
      - './.credentials:/root/.config/gcloud'
    working_dir: /opt/app
    env_file: .env

  builder-base:
    build:
      context: ./builder

  ep-builder:
    extends:
      service: builder-base
    working_dir: /dist/entry-point
    volumes:
      - './entry-point:/app'
      - './dist:/dist'

  sb-builder:
    extends:
      service: builder-base
    working_dir: /dist/sentiment-bot
    volumes:
      - './sentiment-bot:/app'
      - './dist:/dist'
