steps:
  - id: Build Function
    name: 'gcr.io/$PROJECT_ID/$_3_MUSKETEERS_BUILDER_NAME'
    args: ['build_event_handler']

  - id: TF Plan
    name: 'gcr.io/$PROJECT_ID/$_3_MUSKETEERS_BUILDER_NAME'
    env:
      - PROJECT_ID=$PROJECT_ID
      - DOCKER_COMPOSE=docker-compose -f docker-compose.yaml -f docker-compose.gcp.yaml
    args: ['run_plan']

  - id: TF Apply
    name: 'gcr.io/$PROJECT_ID/$_3_MUSKETEERS_BUILDER_NAME'
    env:
      - PROJECT_ID=$PROJECT_ID
      - DOCKER_COMPOSE=docker-compose -f docker-compose.yaml -f docker-compose.gcp.yaml
    args: ['run_apply']

logsBucket: 'gs://contini-7f7bc22cc4c18ffd-build-logs'

options:
  logging: GCS_ONLY
