variable "gcp_project_id" {
  type        = string
  description = "The project id of the project to deploy this gcp infrastructure in"
}

variable "gcp_region" {
  type        = string
  description = "The GCP region to deploy this projects resources in"
}

variable "slack_signing_secret" {
  type        = string
  description = "The slack signing secret generated by slack used to validate that incoming requests originated from slack"
}

variable "slack_oauth_token" {
  type        = string
  description = "The slack bot user OAuth token used to make api calls to slack"
}

variable "alert_email" {
  type        = string
  description = "Email address to send alerts to"
  default     = ""
}
